# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 27 Apr 2022 22:59:56 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

root:$2y$10$hVrVvfqU8hyWw1kKaL2yousiVbwkNpoS7nQ9Na3svM1khgDP6gGTy:kau:kaushikpaddy@gmail.com:admin,user
